### ISSUE TITLE
Chapter 7 - Directive error: The template context does not have an implicit value

### ISSUE THREAD

**Issue by JanuaryLimes** [Apress/pro-angular-6#6]
Hi, I have error in this directive:
https://github.com/Apress/pro-angular-6/blob/master/07%20-%20SportsStore/SportsStore/src/app/store/counter.directive.ts

"The template context does not have an implicit value"

I'm using Angular 7, I know the author suggested to use specific version but there was a promise of "updating" the book and the source code.
   
![zrzut ekranu 2018-11-24 o 21 09 32](https://user-images.githubusercontent.com/15075229/48972571-45338900-f02d-11e8-8cf8-f739fe943384.png)

**Comment by ernestbofill** [comment]
> Change the type of the TemplateRef injected into the directive from type object to CounterDirectiveContext seems to resolve this issue.
> 
> ![image](https://user-images.githubusercontent.com/45842087/50588176-93884300-0e89-11e9-8a51-46f9f3d0185a.png)

Works but I would simplify with an interface.
So line 9 becomes:
`private template: TemplateRef<{$implicit: any}>`

And then the class on line 21 is not necessary
